#+title: Everything You Know Is Wrong
#+date: <2022-01-11 13:35>
#+description: 
#+filetags:

This was one of my mantras, long before I had heard the word “mantra”.

I was one of those insufferable school kids who was always reading ahead, reading outside of the textbook, quietly bored in class.

I was inspired to become a spaceman (before we’d heard that they were called “astronauts”) by Tom Corbet books and on TV, to be a paleontologist by Roy Chapman Andrews’ “All About Dinosaurs”, to be an archaeologist by “All About Prehistoric Cave Men” and to be a geologist by “All About Our Changing Rocks”.

Anne Terry White’s “All About Our Changing Rocks” was to prove my downfall, leading me to become one of those people who “question authority” before that became a bumper sticker. It’s not her fault, not directly. What she wrote in 1955 (and I read when I was eight) was innocent enough. Igneous, sedimentary and metamorphic rocks, erosion, crust and mantle were all innocent enough words and she presented them accurately.

Her role in my demise was to make them so interesting that, in sixth grade, I found an introductory college textbook and read it cover to cover.
