#+title: Does it Matter?
#+date: <2022-02-01 12:06>
#+description: 
#+filetags: truth

Having asked “What is Truth?”, an obvious follow-on question becomes “Does it Matter?” Certainly, sometimes it does, but then again, sometimes it doesn’t.

Whether the answer to a question like “Is this mushroom safe to eat?” is true or false could matter very much if I’m about to pop it into my mouth, whereas a true or false answer to a question like “When will our sun go nova?” isn’t likely to matter in my lifetime.

========================

Written earlier:

What does it matter?

Your correspondant is of a certain age, sex, and background (North American native and citizen, English speaker, educated and well-traveled, living in genteel poverty).

Official sources, elected and non-elected officials, the "official" and alternate media and conversations among family and acquaintences present the issues of the day, month, year and decade.

Ongoing topics of religion, philosophy, politics, history come to mind.

How do I assign priority to my inner life, and which, if any, call for action on my part?





