#+title: News or PR?
#+date: <2022-02-13 13:13>
#+description: 
#+filetags: totd

“Journalism is printing what someone else does not want printed. Everything else is public relations.”—George Orwell — maybe, I can’t find a source — or maybe this:

“News is something somebody doesn’t want printed; all else is advertising.”—William Randolph Hearst — maybe, or maybe Lord Northcliffe (Alfred Harmsworth). Or maybe a whole [[https://quoteinvestigator.com/2013/01/20/news-suppress/][raft of others]].

Orwell seems to be joining Winston Churchill, Mark Twain, the Dalhi Lama, Dr. King and Albert Einstein as the go-to attribution for anything at all. Just remember that Abe Lincoln said, “You can’t trust anything you see on the Internet.” Or my Grandma Smith, “The paper holds still and you can write anything you want on it.”

At any rate, I’d say that there’s an awful lot of PR and advertising in the “newspapers” these days and precious little news/journalism. But that’s just my opinion, your mileage may vary.
