#+title: Does it Matter?
#+date: <2022-02-06 12:06>
#+description: 
#+filetags: truth

Having asked “What is Truth?” and explored the flip side, falsehood, an obvious follow-on question becomes “Does it Matter?” Whether it’s a matter of our own thoughts or what others present to us, does truth or falsehood matter?

Should I be concerned whether I’m being told the truth, or whether I’m being lied to? Whether my own thought processes are in line with “consensus reality” or I’m seriously deluded? Does truth matter?

Certainly, sometimes it does, but then again, sometimes it doesn’t.

If I ask “Is this mushroom safe to eat?” as I’m about to pop it into my mouth, and my friend says, “Sure, perfectly safe” whether that’s true or false could be a matter of life or death. On the other hand, if I say Liv Tyler played Galadriel in the Lord of the Rings movies, and my friend agrees, we’d both be wrong, but it’s not likely to matter much at all — unless I’m about to bet my life savings on the answer.

So, whether telling the truth is important is entirely context-dependent. It depends on the consequences. Or is it? Is there some value to truth, or loss to error, that’s more subtle than these examples would suggest?

That’s a good question and one that’s going to take some more examination. We’ll come back to that one.





