#+title: A Particular Old Laptop
#+date: <2023-02-19 16:49>
#+description: I buy a rebuilt ThinkPad t440
#+filetags: tech

A few days ago I wrote about a) being intrigued by Derek Sivers’ decision to stick with his old (2013) ThinkPad t440s, and b) my self-imposed obligation to try to make my collection of old laptops (the 2001 IBM ThinkPad R32 and 2011 MacBook Pro and HP Elitebook) work well enough to cool my desire for yet another ThinkPad. Well, I’ve been busy.

The MacBook Pro (13” mid-2011) has served me well as a platform that can run Microsoft Office and high-end scanner tools without being (gag) Windows. However, it’s gradually gotten to just not work quite right. I tried the standard thing — reinstalling the OS — which gave me a live Mac which still didn’t work quite right. At that point I got a Cunning Plan — restore from a backup long enough ago that it was still working right. I chose June 30, 2022 out of thin air and did the deed. It took ages, but resulted in a system that came really close to being OK. The trackpad is still Not Quite Right, but I can use the Mac without a mouse now.

The HP went through a similar if somewhat different process. It was running Ubuntu, which I’ve grown over the years to dislike, so the first step was to install Debian. Sounds easy, doesn’t it? I tried installing with a Debian 11 install CD that I’d used on my workstation some months ago, which went as far as installing drivers and locked-up. Old CD, must be scratched. Download the installer, burn a new CD, try again, freeze at the same place. So maybe try a thumb drive. Got it installed, but no WiFi, not a good thing for a laptop. Plus the battery is 100% dead. So I ordered another battery from Amazon and researched the WiFi issue. Seemed to be a firmware issue that can be easily resolved by using an install .iso that includes non-free files. So I downloaded and burned a new thumb drive, and now the WiFi works. And, it’s still not a ThinkPad. The keyboard isn’t better than OK, it has a trackpoint but it doesn’t feel right, and it’s overall angular and a bit heavy. Or am I just working on convincing myself that I Really Need a ThinkPad? I guess so.

I’ve been scanning Amazon and eBay for t440-460s (and that’s “s” for plural), preferably “refurbished” with some guarantee over and above a 30-day return policy. Found a dealer who offers a 30-day free return and 1 year guarantee on its refurbished ex-lease ThinkPads. Looked long and hard at a t440 with 8Mb RAM and a 500GB HDD for $166 — $176 with tax, then Did the Deed, using PayPal Credit for its 6-month zero interest. Should have it by Thursday or Friday, they say. Will be typing with fingers crossed between now and then. It will come with Windows 10 Pro installed, which I am likely to leave when I add Debian 11.
