#+title: About Old Laptops
#+date: <2023-02-13 11:33>
#+description: 
#+filetags: tech

Last week my rss feed showed me a post by ‘Solene’%’ about [[https://dataswamp.org/~solene/2022-06-22-openbsd-selling-arguments.html][”How I would sell OpenBSD as a salesperson”]]. I’m always interested in seeing what other geeks, particularly writers, use for hardware and software. I’ve been more than mildly interested in moving out of Linux back into a “real” UNIX one of these days, which these days means one of the BSDs (FreeBSD, OpenBSD or NetBSD), and so I have a “BSDs” folder in Instapaper and there found links to several pages on Derek Sivers’ site. The one that caught my eye most was [[https://sive.rs/uses][What I Use]].

I relate to Sivers’ approach to tools a lot, since he seems to buy good stuff and then keep it forever, although he’s quite well off and guided by a philosophical preference for buying and owning as little as possible, while I just insist that I’m much poorer than I really am. Parsing his list of hardware, his workstation is a “Silent Desktop PC” is top quality from 2014 (mine is about the same age based on parts from a server that hosted my last project ten years ago). We’re sort of on a par there.

His next entry is his laptop, a Lenovo ThinkPad T440s dating from 2013. That caught my eye. I have a stack of old laptops: two from 2011, a 11” Apple MacBook Pro and an HP Elitebook 8460p, and a 2001 IBM ThinkPad r32. They all work, and they all have issues when it comes to acting like a laptop (that is, allowing me to use Emacs away from my desk). For one thing, they all have battery issues. The HP and the IBM batteries are completely dead, and the Mac’s is very weak. New batteries can be had easily enough, although the Mac would also mean opening the case and getting out my soldering gun.

I’ve never gotten completely comfortable with the Mac. It’s nice hardware - the case is wonderful and the keyboard is acceptable. It’s the software - and mainly MacOS - that I’ve never gotten completely accustomed to. It’s close enough to UNIX/Linux that I can do most of what I want to do, but then it throws a curve into the works that sends me to search for “the Mac way” to finish a job. And by now the trackpad is acting strange and I’m using a mouse when I need to use it to do any scanning. Scanning and Kindle/Calibre are really the only things I use it for these days. I need to take some time off and see whether I can get the trackpad working right again.

The HP is OK, it’s a little loud, a little heavy, the keyboard is kinda clunky. It’s running Ubuntu now, which worked for Valerie when it was her “desktop” but isn’t my cuppa tea. Perhaps with a working battery and a proper Debian installation it could be useful.

That twenty-year-old IBM ThinkPad really is my idea of a laptop I could live with, if it had a newer processor, batteries, wifi and was a little lighter. It might be just that I used ThinkPads during my stay at Northrop Grumman, it has hands-down the best small keyboard, and the track-stick Just Works. That’s why Sivers’ ThinkPad T440s got my attention. It didn’t take long to learn that they are readily available on eBay an Amazon for $250 or less.

So, tempted as I am to just pick one and order it, I feel honor bound to see what I can do to get the MacBook and the HP running right and see whether I can “make do” first.

Stay tuned. I’ve been busy already.
