#+title: Day Six
#+date: <2023-02-08 08:58>
#+description: Nine Days of Prayer for one Deceased
#+filetags: prayer

Nine Days of Prayer for one Deceased — Day Six

For my late brother-in-law, Dr. Dean Presnall

V. Though I walk through the valley of the shadow of death, I shall fear no evil.

R. I will dwell in the house of the Lord forever.

V. Surely your goodness and mercy shall follow me all the days of my life.

R. I will dwell in the house of the Lord forever.

V. Rest eternal grant to them, O Lord;

R. And let light perpetual shine upon them.

OF THE ABUNDANCE of your loving-kindness, O Lord, have mercy upon the soul of your servant Dean and, now that he is released from the weakness of mortality, restore him and give him a place in your everlasting salvation; through Jesus Christ our Lord. /Amen/.

OUR Father, which art in heaven, Hallowed be thy Name. Thy kingdom come. Thy will be done, On earth as it is in heaven. Give us this day our daily bread. And forgive us our trespasses, As we forgive them that trespass against us. And lead us not into temptation, But deliver us from evil. For thine is the kingdom, and the power, and the glory, for ever and ever. /Amen/.

May the souls of the faithful departed, through the mercies of God, rest in peace. /Amen/.
