#+title: The Fourth Sunday in Lent, known as Mothering Sunday
#+date: <2023-03-19 12:33>
#+description: 
#+filetags: liturgy, Lent

Grant, we beseech thee, Almighty God, that we, who for our evil deeds do worthily deserve to be punished, by the comfort of thy grace may mercifully be relieved; through our Lord and Saviour Jesus Christ. /Amen/.

The Fourth Sunday in Lent is known as “Refreshment Sunday” or “Mothering Sunday”. Vestments are rose colored this day.

“During the Middle Ages, it became a custom for British Christians to return to the parish in which they were baptized, their “mother church,” on Mothering Sunday. This highlights an ancient Christian emphasis on baptism as a new birth that is highlighted at the blessing of the font during the Easter Vigil service and is prominent in the baptismal rite itself.

“Beginning in the 15th century, Mothering Sunday became a time to focus on the importance of mothers. On this day, servants were often furloughed to go visit their mothers. Given the celebratory nature of the day, families would often make simnel cakes, a type of fruitcake, as they enjoyed each other’s company.

“Of special interest is the fact that Mothering Sunday falls around the Feast of the Annunciation of the Blessed Virgin Mary, a day when we especially consider the significance of the Theotokos, the Mother of God.”

Thanks to Fr. Wesley Walker for comments on Mothering Sunday.

The Season is Lent, the Liturgical Color is Purple.
