#+title: Day Two
#+date: <2023-02-04 18:11>
#+description: 
#+filetags: prayer

Nine Days of Prayer for One Deceased - Day Two

For my late brother-in-law, Dr. Dean Presnall

V. Though I walk through the valley of the shadow of death, I shall fear no evil.

R. I will dwell in the house of the Lord forever.

V. Surely your goodness and mercy shall follow me all the days of my life.

R. I will dwell in the house of the Lord forever.

V. Rest eternal grant to them, O Lord;

R. And let light perpetual shine upon them.

TO YOU, O LORD, I commend the soul of your servant N., that being dead to the world, he may live to you; and whatever sins he has committed, through the frailty of our mortal nature, graciously wash away by the pardon of your most merciful loving kindness; through Jesus Christ our Lord. /Amen/.

OUR Father, which art in heaven, Hallowed be thy Name. Thy kingdom come. Thy will be done, On earth as it is in heaven. Give us this day our daily bread. And forgive us our trespasses, As we forgive them that trespass against us. And lead us not into temptation, But deliver us from evil. For thine is the kingdom, and the power, and the glory, for ever and ever. /Amen/.

May the souls of the faithful departed, through the mercies of God, rest in peace. /Amen/.
