#+title: Day Five
#+date: <2023-02-07 11:50>
#+description: Nine Days of Prayer for one Deceased
#+filetags: prayer

Nine Days of Prayer for One Deceased — Day Five

For my late brother-in-law, Dr. Dean Presnall

V. Though I walk through the valley of the shadow of death, I shall fear no evil.

R. I will dwell in the house of the Lord forever.

V. Surely your goodness and mercy shall follow me all the days of my life.

R. I will dwell in the house of the Lord forever.

V. Rest eternal grant to them, O Lord;

R. And let light perpetual shine upon them.

GRANT US, WHO MOURN, grace that we may entrust Dean to your never-failing love; receive him into the arms of your mercy, and remember him according to the steadfast loving-kindness you show toward your people; through Jesus Christ our Lord. /Amen/.

OUR Father, which art in heaven, Hallowed be thy Name. Thy kingdom come. Thy will be done, On earth as it is in heaven. Give us this day our daily bread. And forgive us our trespasses, As we forgive them that trespass against us. And lead us not into temptation, But deliver us from evil. For thine is the kingdom, and the power, and the glory, for ever and ever. /Amen/.

May the souls of the faithful departed, through the mercies of God, rest in peace. /Amen/.
