#+title: Our Lady of Walsingham
#+date: <2023-10-16 16:04>
#+description: 
#+filetags: feasts

O GOD, who in the Blessed Virgin Mary didst make a fit dwelling-place for thy Son: grant, we beseech thee, that we who honour her shrine at Walsingham may also become temples of thy Holy Ghost. Through the same Jesus Christ our Lord, who liveth and reigneth with thee, in the unity of the same Holy Ghost, ever one God, world without end. /Amen/.

Sing the praises of Mary, the Mother of God,
Whose Walsingham Way countless pilgrims have trod.

The Season is Trinity, the Liturgical Color is Red. 

The Shrine of Our Lady at Walsingham was established around 1061 when, according to the text of the Pynson Ballad (c 1485), Richeldis de Faverches prayed that she might undertake some special work in honour of Our Lady.

    “ /Our Lady led Richeldis in spirit to Nazareth and showed her the house where the angel had greeted her. ‘Look, daughter’ said Our Lady. ‘Take the measurements of this house and erect another one like it in Walsingham, dedicated to praising and honouring me. All who come there shall find help in their need./

    “ /It shall be a perpetual memorial to the great joy of the Annunciation, ground and origin of all my joys and the root of humanity’s gracious Redemption. This came about through Gabriel’s message that I would be a mother through my humility, and conceive God’s Son in virginity.”  (Pynson Ballad 1485)/

The Lady Richeldis was a holy woman with a great love of the Mother of God. She asked Our Lady for a way to honour her, and it was from this desire in her heart that the events of Walsingham unfolded. Richeldis was not a visionary like the children in Lourdes and Fatima. She was a woman of faith, she pondered, meditated and prayed. In answer to her prayer, the Virgin Mary led her in spirit to Nazareth, showed her the House of the Annunciation where the Angel greeted Mary, and asked her to build a replica in Walsingham as a perpetual memorial of the Annunciation.

This Holy House was built and a religious community took charge of the foundation. Although we have very little historical material from this period, we know that with papal approval the Augustinian Canons built a Priory (c 1150). Walsingham became one of the greatest Shrines in Medieval Christendom.
