#+title: December 30, 2023
#+date: <2023-12-30 09:28>
#+description: 
#+filetags: totd

I am leading you along a way that is uniquely right for you. The closer to Me you grow, the more fully you become your true self—the one I designed you to be. Because you are one of a kind, the path you are traveling with Me diverges increasingly from that of other people. However, in My mysterious wisdom and ways, I enable you to follow this solitary path while staying in close contact with others. In fact, the more completely you devote yourself to Me, the more freely you can love people.

Marvel at the beauty of a life intertwined with My Presence. Rejoice as we journey together in intimate communion. Enjoy the adventure of finding yourself through losing yourself in Me.

/Therefore, if anyone is in Christ, he is a new creation; the old has gone, the new has come!/ — 2 Corinthians 5:17

/For we are God’s workmanship, created in Christ Jesus to do good works, which God prepared in advance for us to do./ — Ephesians 3:10

/Dear frineds, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God. Whoever does not love does not know God, because God is love./ — 1 John 4:7-8

/”Remain in me, and I will remain in you. No branch can bear fruit by itself; it must remain in the vine. Neither can you bear fruit unless you remain in me.”/ — John 15:4

Found in /Jesus Calling/ by Sarah Young
