#+title: St James Apostle and Martyr
#+date: <2023-07-25 08:40>
#+description: 
#+filetags: feasts

GRANT, O merciful God, that, as thine holy Apostle Saint James, leaving his father and all that he had, without delay was obedient unto the calling of thy Son Jesus Christ, and followed him; so we, forsaking all worldly and carnal affections, may be evermore ready to follow thy holy commandments; through the same Jesus Christ our Lord. /Amen/.

The Season is Trinity, the Liturgical Color is Red.

“Now about that time Herod the king stretched forth his hands to vex certain of the church. And he killed James the brother of John with the sword.”—Acts 12:1-2

St. James, from Bethsaida, is called “the Greater” because his vocation to serve Christ preceded that of the other apostle of the same name. He was the son of Zebedee and the brother of John. He was one of the three disciples to witness the Transfiguration (Mt 17:1) and the agony in the Garden (Mt 26:37), aside from other important events of our Saviour’s public life. He and his brother’s impetuous zeal caused the Lord to name them the Sons of Thunder.

James developed his apostolate in Judaea and Samaria. According to tradition he preached the Gospel in Spain. On his return to Palestine about the year 44, he became the first Apostle to suffer martyrdom, at the order of Herod Agrippa. His mortal remains were later brought to Santiago de Compostela, in Spain, which became a popular medieval pilgrimage site and a sanctuary of the Faith for all of Europe
