#+title: Nine Days of Prayer for one Deceased — Day Eight
#+date: <2023-02-10 10:18>
#+description: Nine Days of Prayer for one Deceased
#+filetags: prayer

For my late brother-in-law, Dr. Dean Presnall

V. Though I walk through the valley of the shadow of death, I shall fear no evil.

R. I will dwell in the house of the Lord forever.

V. Surely your goodness and mercy shall follow me all the days of my life.

R. I will dwell in the house of the Lord forever.

V. Rest eternal grant to them, O Lord;

R. And let light perpetual shine upon them.

O LORD, OUR SAVIOR AND OUR JUDGE, by your passion and through your never failing mercies, grant forgiveness to Dean for all his sins, and rest from all the burdens he has carried; and by your Spirit, bring us all to acknowledge our sins that we may seek your forgiveness and make us patient and joyful to forgive one another for your sake; through Jesus Christ our Lord. /Amen/.

OUR Father, which art in heaven, Hallowed be thy Name. Thy kingdom come. Thy will be done, On earth as it is in heaven. Give us this day our daily bread. And forgive us our trespasses, As we forgive them that trespass against us. And lead us not into temptation, But deliver us from evil. For thine is the kingdom, and the power, and the glory, for ever and ever. /Amen/.

May the souls of the faithful departed, through the mercies of God, rest in peace. /Amen/.
