#+title: In the latter times some shall depart
#+date: <2023-10-23 10:50>
#+description: 
#+filetags: readings

“Now the Spirit speaketh expressly, that in the latter times some shall depart from the faith, giving heed to seducing spirits, and doctrines of devils; Speaking lies in hypocrisy; having their conscience seared with a hot iron; Forbidding to marry, and commanding to abstain from meats, which God hath created to be received with thanksgiving of them which believe and know the truth.” I Timothy 4: 1-3

Found in the second reading at Matins, and which brought me up short for a moment. Of course, now is surely not the first time after St Timothy read this that those words could describe the situation of the surrounding culture, or even the condition of Christ’s Church, but it certainly seems to describe recont conditions, Marriage certainly is declining, even among those who cohabit, and there seem to be more, at least in G20 countries, who are choosing (or finding themselves) unable or unwilling to cohabit, and even among those who marry fewer are willing to “go forth and multiply”. Perhaps it is “commanding to abstain from meats” that first struck me, with the talk, by the WEF and the Green religionists, that we will eat no real meat lest we destroy the Earth. All of which throws me back the CSL’s /That Hideous Strength/ and the ever clearer vision of demons leading humans around by the nose. And of course we are told that no man knows, inclusing CSL and me. So that’s that.
