#+title: Day One
#+date: <2023-02-03 18:05>
#+description: Nine Days of Prayer for one Deceased
#+filetags: prayer

Nine Days of Prayer for One Deceased — Day One

For my late brother-in-law, Dr. Dean Presnall

V. Though I walk through the valley of the shadow of death, I shall fear no evil.

R. I will dwell in the house of the Lord forever.

V. Surely your goodness and mercy shall follow me all the days of my life.

R. I will dwell in the house of the Lord forever.

V. Rest eternal grant to them, O Lord;

R. And let light perpetual shine upon them.

O GOD, YOU ARE FULL OF MERCY and ready to forgive; receive our prayers for the soul of your servant Dean, whom you have now called to depart out of this world: deliver him out of the hand of the enemy, hold him in everlasting remembrance, and command your holy angels to receive him and bring him into paradise: that as his hope and faith were in you, he may without fear or suffering enter the joys of eternal life; through Jesus Christ our Lord. /Amen/.

OUR Father, which art in heaven, Hallowed be thy Name. Thy kingdom come. Thy will be done, On earth as it is in heaven. Give us this day our daily bread. And forgive us our trespasses, As we forgive them that trespass against us. And lead us not into temptation, But deliver us from evil. For thine is the kingdom, and the power, and the glory, for ever and ever. /Amen/.

May the souls of the faithful departed, through the mercies of God, rest in peace. /Amen/.
