#+title: Day Nine
#+date: <2023-02-11 22:26>
#+description: Nine Days of Prayer for one Deceased
#+filetags: prayer

Nine Days of Prayer for one Deceased — Day Nine

For my late brother-in-law, Dr. Dean Presnall

V. Though I walk through the valley of the shadow of death, I shall fear no evil.

R. I will dwell in the house of the Lord forever.

V. Surely your goodness and mercy shall follow me all the days of my life.

R. I will dwell in the house of the Lord forever.

V. Rest eternal grant to them, O Lord;

R. And let light perpetual shine upon them.

I GIVE YOU THANKS, O Lord, that you have created us to know and love you, and to live with each other in joyful companionship. In grief, strengthen my hope, and in sorrow, keep me from despair. Grant that Dean may go from strength to strength in the life of perfect service, and that I may so serve you here, that at the last, by your call, I will stand before you and with those whom I have loved but see no longer; through Jesus Christ our Lord. /Amen/.

OUR Father, which art in heaven, Hallowed be thy Name. Thy kingdom come. Thy will be done, On earth as it is in heaven. Give us this day our daily bread. And forgive us our trespasses, As we forgive them that trespass against us. And lead us not into temptation, But deliver us from evil. For thine is the kingdom, and the power, and the glory, for ever and ever. /Amen/.

May the souls of the faithful departed, through the mercies of God, rest in peace. /Amen/
