#+title: Ezekiel 33:1-9
#+date: <2024-01-23 12:43>
#+description: 
#+filetags: totd

Again the word of the LORD came unto me, saying, Son of man, speak to the children of thy people, and say unto them, When I bring the sword upon a land, if the people of the land take a man of their coasts, and set him for their watchman: If when he seeth the sword come upon the land, he blow the trumpet, and warn the people; Then whosoever heareth the sound of the trumpet, and taketh not warning; if the sword come, and take him away, his blood shall be upon his own head. He heard the sound of the trumpet, and took not warning; his blood shall be upon him. But he that taketh warning shall deliver his soul.

But if the watchman see the sword come, and blow not the trumpet, and the people be not warned; if the sword come, and take any person from among them, he is taken away in his iniquity; but his blood will I require at the watchman's hand.

So thou, O son of man, I have set thee a watchman unto the house of Israel; therefore thou shalt hear the word at my mouth, and warn them from me. When I say unto the wicked, O wicked man, thou shalt surely die; if thou dost not speak to warn the wicked from his way, that wicked man shall die in his iniquity; but his blood will I require at thine hand.

Nevertheless, if thou warn the wicked of his way to turn from it; if he do not turn from his way, he shall die in his iniquity; but thou hast delivered thy soul.

....

This is the first lesson for Evensong on the Tuesday after the 3rd Sunday after Epiphany. It raises the question what it means for those of us who are not a “man of the coast” whom the people of the land have set up for their watchman. If we are inland and anonymous to our fellows and see the sword coming upon the land, are we called upon to sound the trumpet? Is this solely speaking to capital-P Prophets like Ezekiel? Or perhaps only to the Ezekiel who lived in Nippur in the 6th century B.C.?

If I am a Christian living in the 21st century A.D., doing my best, or at least trying somewhat, to do God’s will, and I see what seems to be a sword (or a large variety of swords), am I called to ignore it/them and carry on with my daily tasks, or am I called in some way to “sound the trumpet”?
