#+title: The Presentation of Christ, or Candlemas
#+date: <2024-02-02 22:54>
#+description: 
#+filetags: feast Pre-Lent

ALMIGHTY and everliving God, we humbly beseech thy Majesty, that, as thy only-begotten Son was this day presented in the temple in substance of our flesh, so we may be presented unto thee with pure and clean hearts, by the same thy Son Jesus Christ our Lord. /Amen/.

The Season is Pre-Lent, the liturgical color of the day is /White/.

Canadian journalist and Catholic blogger David Warren writes:

Today, the fortieth and last of Christmas, is once again “Candlemas.” It commemorates the presentation of the child Jesus in the Temple at Jerusalem, along with the sacrifice of Joseph and Mary, who could not afford a lamb. The feast also commemorates the conclusion of the forty-day cycle for the purification of a mother, according to Hebraic custom. A poor Jewish couple with their firstborn, acting according to ancient Mosaic law; greeted by Anne, and by the prophetic Simeon, who utters the /Nunc Dimittis/:

“Lord, now lettest thou thy servant depart in peace, according to thy word. For mine eyes have seen thy salvation, which thou hast prepared before the face of all people; a light to lighten the Gentiles, and the glory of thy people Israel.”

I was an Anglican too many years to abandon this splendid English rendering of the Scripture, the third of Saint Luke’s great canticles (after the Magnificat and the Benedictus). The Latin is good and the Greek is better. The poetry of the words is fully necessary. They are intended to convey the poignancy of the scene, in the face of this old man, who has recognized his Messiah, to the amazement of the child’s own parents.

It was from this canticle that the Greeks named the feast, Hypapante, referring to this moment of recognition by the Old, of the New. Tired and waiting for death, standing himself at the junction of worlds, the eyes of Simeon see that nothing will be the same. The Messiah has come, and the whole course of history that must follow flickers in the old man’s eyes, still bound in the breath of a moment to this blessed Earth, and the dimension of Time. It is the canticle I read over my own father’s grave, as we committed him, dust to dust.

There is, I am sure, theological significance in each of the events that combine to be celebrated within Candlemas — in the procession and the blessing of the candles. The fulfilment of that ancient law, drawn from the pages of Leviticus, is again before us.

I like to think on the two turtle doves: the gift to the Temple that this couple, Joseph and Mary, could actually afford. The simplicity of it, alongside the incomprehensible gift of Jesus.

Christ has come to fulfil the laws of Moses, and the Law behind all law. It makes no sense that He should be here, that He should arrive in this human form, in the arms of this young mother. The ancient imagination demanded that a Saviour come in timpani and trumpets. Here is this small child, and these impoverished parents, with their brace of pigeons in a stick cage. They stand at the intersection of all Time.

The Author of all we know, has sent so personal a Gift, by such messengers, as the fulfilment of His promise to Abraham. I find this astonishing; indeed, too preposterous not to be true. That He is presenting Himself, helpless at the Temple, in fulfilment of an ancient vow. I find it very odd. For what does this gesture suggest?

The humility of a Lover.
