#+title: The Fifth Sunday After Easter, Commonly Called Rogation Sunday
#+date: <2025-05-25 22:06>
#+description: 
#+filetags: liturgy Eastertide

O Lord, from whom all good things do come; Grant to us thy humble servants, that by thy holy inspiration we may think those things that are good, and by thy merciful guiding may perform the same; through our Lord Jesus Christ. /Amen/.

The Season is Eastertide, the Liturgical Color is /White/.

“Rogation” comes from the Latin verb /rogare/, meaning “to ask”. There are two phases of Rogation Days, the “major” on 25 April, and the “minor”, Monday through Wednesday before Ascension Thursday.

On Rogation Days, with fasting, processions and the singing of the Litany of Saints, we ask God to protect us from danger. One danger in the ancient world was crop failure. Indeed, our Christian Rogation Days tradition stems from the pagan Roman practice of the Robigalia procession on 25 April with, among other weird things, the sacrifice of a dog to the god (really a demon) Robigus against wheat rust, a disease that attacked that precious crop. By the 5th century here and there in France, Christians had replaced all the pagan stuff with goodly uses. The practice spread in a wholesome way as wholesome practices did. Pope Leo III (+816) incorporated the Rogation Days into the Roman Rite. So, we’ve had them for well over a thousand years, give or take a century.

/Notes on Rogation taken from [[https://onepeterfive.com/5th-sunday-after-easter-lies/][onepeter5.com]]/
