#+title: Good Friday
#+date: <2025-04-18 22:31>
#+description: 
#+filetags: liturgy Lent

ALMIGHTY God, we beseech thee graciously to behold this thy family, for which our Lord Jesus Christ was contented to be betrayed, and given up into the hands of wicked men, and to suffer death upon the cross; who now liveth and reigneth with thee and the Holy Ghost ever, one God, world without end. /Amen/.

ALMIGHTY and everlasting God, by whose Spirit the whole body of the Church is governed and sanctified; Receive our supplications and prayers, which we offer before thee for all estates of men in thy holy Church, that every member of the same, in his vocation and ministry, may truly and godly serve thee; through our Lord and Saviour Jesus Christ. /Amen/.

MERCIFUL God, who hast made all men, and hatest nothing that thou hast made, nor desirest the death of a sinner, but rather that he should be converted and live; Have mercy upon all who know thee not as thou art revealed in the Gospel of thy Son. Take from them all ignorance, hardness of heart, and contempt of thy Word; and so fetch them home, blessed Lord, to thy fold, that they may be made one flock under one shepherd, Jesus Christ our Lord, who liveth and reigneth with thee and the Holy Spirit, one God, world without end. /Amen/. 

The Season is Lent, the liturgical color of the day is /Black/.
